# A Travis CI configuration file.

sudo: required

language:
  - scala
  - node_js

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false

install: true

before_install:
  - ./tools/travis/setup.sh
  - ./tools/travis/scan.sh

script:
  - "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/deploy_wskdeploy.sh && ./tools/travis/test.sh"
